name: Build project
on:
  push:

permissions:
  packages: write

jobs:
  build-image:
    name: Run Jib builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        env:
          QUARKUS_JIB_BASE_REGISTRY_USERNAME: ${{ github.actor }}
          QUARKUS_JIB_BASE_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          QUARKUS_CONTAINER_IMAGE_ADDITIONAL_TAGS: latest
        run: mvn -Dquarkus.container-image.registry=ghcr.io -Dquarkus.container-image.name=poker-tracker -Dquarkus.container-image.group=fatih-catalkaya -Dquarkus.container-image.push=true quarkus:image-build
